import re
from typing import Annotated

from fastapi import APIRouter, Depends, Query, Request
from redis.asyncio import Redis

from app.application.services.traffic_service import record_ping
from app.core.cache import get_redis
from app.core.client_ip import get_client_ip
from app.core.config import get_settings
from app.core.rate_limit import RateLimiter

router = APIRouter(prefix="/traffic", tags=["traffic"])

# Visitor IDs are UUID v4 strings generated by the frontend (localStorage).
# We accept only the safe UUID character set to prevent Redis key injection
# or log-spam via crafted visitor IDs.
_VISITOR_ID_RE = re.compile(r"^[0-9a-f\-]{1,36}$", re.IGNORECASE)

# Public, unauthenticated endpoint — cap pings per IP so the visitor counters
# can't be inflated or used to hammer Redis.
_ping_limiter = RateLimiter(
    times=get_settings().rate_limit_ping_per_minute, scope="traffic-ping"
)


@router.post("/ping", status_code=204, dependencies=[Depends(_ping_limiter)])
async def ping(
    request: Request,
    redis: Annotated[Redis, Depends(get_redis)],
    visitor_id: Annotated[str | None, Query(max_length=36)] = None,
) -> None:
    """Called by the frontend on page load. visitor_id is a stable anonymous id
    generated client-side (stored in localStorage). Falls back to IP."""
    vid = (
        visitor_id
        if visitor_id and _VISITOR_ID_RE.match(visitor_id)
        else get_client_ip(request)
    )
    await record_ping(redis, vid)
