import re
from typing import Annotated

from fastapi import APIRouter, Depends, Query, Request
from redis.asyncio import Redis

from app.application.services.traffic_service import record_ping
from app.core.cache import get_redis

router = APIRouter(prefix="/traffic", tags=["traffic"])

# Visitor IDs are UUID v4 strings generated by the frontend (localStorage).
# We accept only the safe UUID character set to prevent Redis key injection
# or log-spam via crafted visitor IDs.
_VISITOR_ID_RE = re.compile(r"^[0-9a-f\-]{1,36}$", re.IGNORECASE)


@router.post("/ping", status_code=204)
async def ping(
    request: Request,
    redis: Annotated[Redis, Depends(get_redis)],
    visitor_id: Annotated[str | None, Query(max_length=36)] = None,
) -> None:
    """Called by the frontend on page load. visitor_id is a stable anonymous id
    generated client-side (stored in localStorage). Falls back to IP."""
    if visitor_id and _VISITOR_ID_RE.match(visitor_id):
        vid = visitor_id
    else:
        vid = (request.client.host if request.client else None) or "unknown"
    await record_ping(redis, vid)
